# Generated by Django 4.1.3 on 2022-12-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_deckplayera_deckplayerb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeckPlayerA',
        ),
        migrations.DeleteModel(
            name='DeckPlayerB',
        ),
    ]
