# Generated by Django 4.1.3 on 2022-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_deckplayera_deckplayerb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeckPlayerA',
        ),
        migrations.DeleteModel(
            name='DeckPlayerB',
        ),
        migrations.AddField(
            model_name='card',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
