# Generated by Django 4.1.3 on 2022-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_delete_deckplayera_delete_deckplayerb_card_is_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
