# Generated by Django 4.1.3 on 2022-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Red', max_length=20)),
                ('image', models.ImageField(blank=True, default='B-Red.png', null=True, upload_to='')),
            ],
        ),
    ]
