# Generated by Django 4.1.3 on 2022-12-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coin',
            field=models.IntegerField(default=1000),
        ),
    ]
